import LegalLayout from '@/components/legal/LegalLayout';

export default function Disclaimer() {
  return (
    <LegalLayout 
      title="Legal Disclaimer" 
      description="Legal Disclaimer for ThreadLock - Important information about using our service"
    >
      <p className="text-sm text-gray-500 mb-6">
        <strong>Effective Date:</strong> [EFFECTIVE DATE]
      </p>

      <h2 className="text-2xl font-bold mt-8 mb-4">1. Not a Law Firm</h2>
      <p className="mb-4">
        ThreadLock is a technology company, not a law firm. We do not provide legal services, legal advice, or legal representation. 
        Nothing on this website or in our Service should be construed as legal advice.
      </p>

      <h2 className="text-2xl font-bold mt-8 mb-4">2. AI-Generated Content Disclaimer</h2>
      <p className="mb-4">
        ThreadLock uses artificial intelligence (AI) to provide suggestions, guidance, and assistance with evidence organization. 
        <strong> AI-generated content is for informational purposes only and should not be relied upon as legal advice.</strong>
      </p>
      <p className="mb-4">
        AI systems can make mistakes, provide incomplete information, or generate content that may not be applicable to your 
        specific situation. You should:
      </p>
      <ul className="list-disc pl-6 mb-4">
        <li>Carefully review all AI-generated content</li>
        <li>Verify information independently</li>
        <li>Consult with a qualified attorney before taking any legal action</li>
        <li>Not rely solely on AI suggestions for legal decisions</li>
      </ul>

      <h2 className="text-2xl font-bold mt-8 mb-4">3. Consult a Licensed Attorney</h2>
      <p className="mb-4">
        <strong>You should always consult with a qualified, licensed attorney for legal advice specific to your situation.</strong>
      </p>
      <p className="mb-4">
        Every legal situation is unique, and laws vary by jurisdiction. Only a licensed attorney who is familiar with your 
        specific circumstances and local laws can provide appropriate legal advice.
      </p>

      <h2 className="text-2xl font-bold mt-8 mb-4">4. No Attorney-Client Relationship</h2>
      <p className="mb-4">
        Use of the ThreadLock Service does not create an attorney-client relationship between you and ThreadLock or any 
        of its employees, contractors, or affiliates.
      </p>

      <h2 className="text-2xl font-bold mt-8 mb-4">5. Information Provided "As Is"</h2>
      <p className="mb-4">
        All information provided through the Service is for general informational purposes only and is provided "as is" 
        without warranty of any kind. We make no representations or warranties about:
      </p>
      <ul className="list-disc pl-6 mb-4">
        <li>The accuracy, completeness, or reliability of information</li>
        <li>The suitability of AI-generated suggestions for your specific situation</li>
        <li>The legal validity or admissibility of documents created using the Service</li>
        <li>Outcomes in legal proceedings</li>
      </ul>

      <h2 className="text-2xl font-bold mt-8 mb-4">6. Court Admissibility</h2>
      <p className="mb-4">
        While ThreadLock is designed to help you organize and present evidence, we cannot guarantee that any evidence, 
        documents, or exports generated by the Service will be admissible in court or accepted by any legal authority.
      </p>
      <p className="mb-4">
        Rules of evidence vary by jurisdiction and court. You should consult with an attorney to ensure your evidence 
        meets the requirements of your specific legal proceeding.
      </p>

      <h2 className="text-2xl font-bold mt-8 mb-4">7. User Responsibility</h2>
      <p className="mb-4">
        You are solely responsible for:
      </p>
      <ul className="list-disc pl-6 mb-4">
        <li>The accuracy of information you provide to the Service</li>
        <li>Decisions you make based on information from the Service</li>
        <li>Compliance with all applicable laws and court rules</li>
        <li>Seeking appropriate legal counsel</li>
        <li>Verifying the accuracy of AI-generated content</li>
      </ul>

      <h2 className="text-2xl font-bold mt-8 mb-4">8. No Guarantee of Results</h2>
      <p className="mb-4">
        Use of the Service does not guarantee any particular outcome in legal proceedings. The success of your case depends 
        on many factors beyond the scope of this Service, including the facts of your case, applicable law, the court, 
        and the quality of your legal representation.
      </p>

      <h2 className="text-2xl font-bold mt-8 mb-4">9. External Links</h2>
      <p className="mb-4">
        The Service may contain links to external websites or resources. We do not endorse and are not responsible for the 
        content, accuracy, or practices of third-party websites. Access to external links is at your own risk.
      </p>

      <h2 className="text-2xl font-bold mt-8 mb-4">10. Jurisdictional Variations</h2>
      <p className="mb-4">
        Laws, procedures, and rules vary significantly by jurisdiction. Information provided by the Service may not be 
        applicable or accurate in your jurisdiction. Always verify information with a local attorney.
      </p>

      <h2 className="text-2xl font-bold mt-8 mb-4">11. Updates and Changes</h2>
      <p className="mb-4">
        Legal standards and requirements change over time. Information that was accurate when provided may become outdated. 
        We are not obligated to update information or notify you of changes in the law.
      </p>

      <h2 className="text-2xl font-bold mt-8 mb-4">12. Contact Information</h2>
      <p className="mb-4">
        If you have questions about this Disclaimer, please contact us at:
      </p>
      <p className="mb-4">
        <strong>Email:</strong> [CONTACT EMAIL]
      </p>

      <h2 className="text-2xl font-bold mt-8 mb-4">13. Related Policies</h2>
      <ul className="list-disc pl-6 mb-4">
        <li><a href="/terms" className="text-orange-600 hover:text-orange-700 underline">Terms of Service</a></li>
        <li><a href="/privacy" className="text-orange-600 hover:text-orange-700 underline">Privacy Policy</a></li>
      </ul>
    </LegalLayout>
  );
}
