name: Marketing Quality Checks

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint marketing layout consistency
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run ESLint
        run: npm run lint

  cypress:
    runs-on: ubuntu-latest
    name: E2E visual consistency test
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build Next.js app
        run: npm run build
        env:
          # Suppress Firebase warnings during build
          NEXT_PUBLIC_FIREBASE_API_KEY: dummy
          NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: dummy
          NEXT_PUBLIC_FIREBASE_PROJECT_ID: dummy
          NEXT_PUBLIC_FIREBASE_APP_ID: dummy
          NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: dummy
      
      - name: Start Next.js server
        run: npm start &
        env:
          NEXT_PUBLIC_FIREBASE_API_KEY: dummy
          NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: dummy
          NEXT_PUBLIC_FIREBASE_PROJECT_ID: dummy
          NEXT_PUBLIC_FIREBASE_APP_ID: dummy
          NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: dummy
      
      - name: Wait for server
        run: npx wait-on http://localhost:3000 --timeout 60000
      
      - name: Run Cypress tests
        run: npx cypress run --spec "cypress/e2e/layout_consistency.cy.ts"
      
      - name: Upload Cypress screenshots on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots
          path: cypress/screenshots
          if-no-files-found: ignore
      
      - name: Upload Cypress videos
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos
          path: cypress/videos
          if-no-files-found: ignore
