name: Marketing Quality Checks

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint marketing layout consistency
    permissions:
      contents: read
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run ESLint
        run: npm run lint

  cypress:
    runs-on: ubuntu-latest
    name: E2E visual consistency test
    permissions:
      contents: read
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build Next.js app
        run: npm run build
        env:
          # Suppress Firebase warnings during build
          NEXT_PUBLIC_FIREBASE_API_KEY: dummy
          NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: dummy
          NEXT_PUBLIC_FIREBASE_PROJECT_ID: dummy
          NEXT_PUBLIC_FIREBASE_APP_ID: dummy
          NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: dummy
      
      - name: Start Next.js server
        run: |
          nohup npm start >/dev/null 2>&1 &
          echo $! > .next_pid
        env:
          NEXT_PUBLIC_FIREBASE_API_KEY: dummy
          NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: dummy
          NEXT_PUBLIC_FIREBASE_PROJECT_ID: dummy
          NEXT_PUBLIC_FIREBASE_APP_ID: dummy
          NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: dummy
      
      - name: Wait for server
        run: npx wait-on http://localhost:3000 --timeout 60000
      
      - name: E2E visual consistency
        env:
          NODE_OPTIONS: ""
          CYPRESS_INSTALL_BINARY: "0"
        run: npm run e2e:spec
      
      - name: Upload Cypress results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-results
          path: |
            cypress/results/**/*.xml
            cypress/screenshots/**
            cypress/videos/**
          if-no-files-found: ignore
      
      - name: Stop Next.js server
        if: always()
        run: |
          if [ -f .next_pid ]; then kill $(cat .next_pid) || true; fi
